# Generated by Django 4.1.3 on 2022-11-25 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
