# Generated by Django 4.1.3 on 2022-11-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('EX', 'Expense'), ('CH', 'Chore')], max_length=2)),
                ('is_passed', models.BooleanField()),
                ('title', models.CharField(max_length=127)),
                ('recur', models.BooleanField()),
                ('recur_freq', models.DateTimeField()),
                ('time_range', models.DurationField()),
            ],
        ),
    ]
