# Generated by Django 4.1.3 on 2022-11-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
