# Generated by Django 4.1.3 on 2023-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commune_app', '0001_alter_user_groups_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='',
                                         related_name='user_set',
                                         related_query_name='user',
                                         to='auth.group',
                                         verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='', verbose_name='active'),
        ),
    ]
