# Generated by Django 4.1.3 on 2023-01-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commune_app', '0002_add_user_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=False,
                max_length=150,
                verbose_name='first name'
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to.'
                + 'A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.group',
                verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(
                auto_created=False,
                primary_key=True,
                serialize=False,
                verbose_name='ID'
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active.'
                + 'Unselect this instead of deleting accounts.',
                verbose_name='active'
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether the user can log into this admin site.',
                verbose_name='staff status'
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=False,
                max_length=150,
                verbose_name='last name'
                ),
        ),
    ]
