# Generated by Django 4.1.3 on 2023-01-08 16:06

import commune_app.all_models.communes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commune_app', '0003_createsuperuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='wallet',
            field=models.IntegerField(
                default=0,
                validators=[commune_app.all_models.communes.validate_wallet]
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to.'
                + 'A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.group',
                verbose_name='groups'
                ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active.'
                + 'Unselect this instead of deleting accounts.',
                verbose_name='active'
                ),
        ),
    ]
