# Generated by Django 4.1.3 on 2023-01-03 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commune_app', '0005_alter_user_groups_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to.'
                + ' A user will get all permissions granted to each of their groups.',
                related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Designates whether this user should be treated as active.'
                + ' Unselect this instead of deleting accounts.', verbose_name='active'
            ),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_app.chore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
