# Generated by Django 4.1.3 on 2023-01-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune_app', '0006_alter_user_groups_alter_user_is_active_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('wallet', models.IntegerField(default=0)),
            ],
        ),
    ]
