# Generated by Django 4.1.3 on 2023-01-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commune_app', '0006_alter_user_groups_alter_user_is_active_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('wallet', models.IntegerField()),
                ('name', models.TextField()),
                ('chores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_app.chore')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commune_app.vote')),
            ],
        ),
    ]
