# Generated by Django 4.1.3 on 2023-01-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commune_app', '0007_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='Commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune_app.commune'),
        ),
        migrations.AddField(
            model_name='user',
            name='Commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commune_app.commune'),
        ),
    ]
